import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import styles from '../styles/Home.module.css'
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
    <Head>
      <title> Developers' Blog</title>
      <meta name="description" content="Generated by create next app"/>
      
    </Head>
    <main
      className={`flex min-h-screen flex-col items-center justify-start p-10 ${inter.className}`}
    >
     
      <h1 className="text-5xl text-black font-bold my-10"> Developers Blog</h1>
      <Image className="rounded-3xl" src= {'/coder.avif'} height={200} width={300} alt="background_image"/>
      <p className="p-10 text-xl">A help area for developers.</p>
    </main>
    </>
  );
}
